const SETTING_TOGGLE_THEME = "SETTING_TOGGLE_THEME"
const SETTING_CHANGE_LANGUAGE = "SETTING_CHANGE_LANGUAGE"
const RUN_SPIN = "RUN_SPIN"
const STOP_SPIN = "STOP_SPIN"
const SETTING_USER_INFO = "SETTING_USER_INFO"

export { SETTING_TOGGLE_THEME, SETTING_CHANGE_LANGUAGE, RUN_SPIN, STOP_SPIN, SETTING_USER_INFO }